# -----------------------------------------------
# This file was generated by the acts_as_authenticated_user plugin
# Edit as needed ...
#
# More details at http://www.theworkinggroup.ca/rails/plugins/wristband
# -----------------------------------------------
class UserNotifier < ActionMailer::Base
  # Define on you config/environments folder:
  # development: 
  #   HOST_NAME = 'localhost:3000'
  #   SITE_URL = 'http://localhost:3000'
  #   FROM_EMAIL = 'your_email@your_domain.com'
  # test: 
  #   HOST_NAME = 'localhost:3000'
  #   SITE_URL = 'http://localhost:3000'
  #   FROM_EMAIL = 'your_email@your_domain.com'
  # staging: 
  #   HOST_NAME = 'staging.yourapp.com'
  #   SITE_URL = 'http://staging.yourapp.com'
  #   FROM_EMAIL = 'info@staging.yourapp.com'
  # production: 
  #   HOST_NAME = 'yourapp.com'
  #   SITE_URL = 'http://www.yourapp.com'
  #   FROM_EMAIL = 'info@yourapp.com'
  
  default_url_options[:host] = HOST_NAME
  
  def email_verification(user)
    setup_email(user)
    @subject         += "Your account has been created. Please verify your email address"
  end  

  def forgot_password(user)
    setup_email(user)
    @subject          += "You have requested a new password"
  end


protected
  # Change YourApp to whatever you application is called
  def setup_email(user)
    @recipients  = user.email
    @body[:user] = user
    @from        = FROM_EMAIL
    @subject = case ENV['RAILS_ENV'] 
      when 'development': "[YourApp Development] "
      when 'staging': "[YourApp Staging] "
      else "[YourApp] "
    end
    @sent_on     = Time.now
    headers       "Reply-to" => FROM_EMAIL
  end

end