# -----------------------------------------------
# This file was generated by the acts_as_authenticated_user plugin
# Edit as needed ...
#
# More details at http://www.theworkinggroup.ca/rails/plugins/wristband
# -----------------------------------------------
class User < ActiveRecord::Base
  
  # Add your own stuff here...
  # Possible options are:
  #
  # :login_with 
  #     The fields a user will be validated againts.
  #     Defaults to :username
  #
  # :password_column 
  #     Sets the name of your password column.
  #     If :plain_text_password => true it defaults to :password otherwise it defaults to :password_crypt
  #
  # :plain_text_password 
  #     Defaults to false
  #
  # :before_authentication 
  #     Stuff you may want to do before authentication
  #
  # :after_authentication 
  #     Stuff you may want to do after authentication
  #
  wristband
end
