# -----------------------------------------------
# This file was generated by the wristband plugin
# Edit as needed ...
#
# More details at http://www.theworkinggroup.ca/rails/plugins/wristband
# -----------------------------------------------
class CreateWristbandTables < ActiveRecord::Migration
  def self.up
    create_table :users do |t|
      # uncomment if you want a username in addition to an email
      # t.string :username
      t.string :email
      t.string :password_crypt, :limit => 40
      t.string :password_salt,  :limit => 40
      t.string :remember_token
      t.string :email_validation_key
      t.datetime :validated_at
      t.string :role
      t.datetime :created_at
      t.datetime :updated_at
      # Add your own stuff here ...
    end
  end
  
  def self.down
    drop_table :users
  end
end
