# -----------------------------------------------
# This file was generated by the acts_as_authenticated_user plugin
# Edit as needed ...
#
# More details at http://www.theworkinggroup.ca/rails/plugins/wristband
# -----------------------------------------------
class SessionsController < ApplicationController
  
  # login_required is defined by the wristband plugin
  # if the user is not logged in it will call respond_not_logged_in
  before_filter :login_required,        :only => :destroy
  
  # This one is just usefull to have
  before_filter :redirect_if_logged_in, :only => [:new, :create]
  
  def new
    # ...
  end

  # Logs the user in
  # Adjust as necessary
  def create
    if @user = authenticate_and_login(params[:user][:username], params[:user][:password], params[:user][:remember_me]=='1')
      flash[:notice] = "Welcome, you are now logged in."
      redirect_to users_path
    else
      flash[:notice] = 'Login failed.'
      redirect_to login_path
    end
  end
  
  # Logs out the user 
  # Adjust as necessary
  def destroy
    logout
    redirect_to home_path 
  end
  
private
  def redirect_if_logged_in
    redirect_to home_path if logged_in?
  end
  
  # This will be called by the login_required filter when the user is not logged in
  # You can replace this with whatever you want.
  # You can also move this to Application controller so it can be shared with other controllers.
  def respond_not_logged_in
    redirect_to login_path
  end
end
