# ---------------------------------------------------------------------------
#
# This file was generated by the wristband plugin and should be customized.
#
# More details at: http://github.com/theworkinggroup/wristband/tree/master
#
# ---------------------------------------------------------------------------
class SessionsController < ApplicationController
  
  # login_required is defined by the wristband plugin
  # If the user is not logged in it will call respond_not_logged_in
  before_filter :login_required,
    :only => :destroy
  
  # This is just useful to have
  before_filter :redirect_if_logged_in,
    :only => [ :new, :create ]
  
  def new
    # Customize as required
  end

  # Logs the user in
  # Adjust as necessary
  def create
    user_params = params[:user]
    
    if (@user = user_params && authenticate_and_login(user_params[:username], user_params[:password], user_params[:remember_me] == '1'))
      flash[:notice] = "Welcome, you are now logged in."
      redirect_to users_path
    else
      flash[:notice] = 'Login failed.'
      redirect_to login_path
    end
  end
  
  # Logs out the user 
  def destroy
    logout
    redirect_to home_path
  end
  
private
  def redirect_if_logged_in
    redirect_to home_path if logged_in?
  end
  
  # This will be called by the login_required filter when the user is not logged in
  # You can replace this with whatever you want.
  # You can also move this to Application controller so it can be shared with other controllers.
  def respond_not_logged_in
    redirect_to login_path
  end
end
